apiVersion: 1

datasources:
  - name: Machine Monitoring Postgres
    uid: machine_monitoring_postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: monitoring_user
    secureJsonData:
      password: monitoring_password
    jsonData:
      database: machine_monitoring
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true
